/*
 * EnterOtherOptions.java
 *
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
/**
 *
 * @author  arunprasath shankar
 */
public class EnterOtherOptions extends WizardPanel {

    private int quality;
    private String comment, password;
    private String embededText;

    /**
     * Creates new form EnterOtherOptions
     */
    public EnterOtherOptions(String display) {
        super(display);
        initComponents();
        setFirstFocusable(passwordField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        passwordPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        encryptButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setLayout(new java.awt.BorderLayout());

        passwordPanel.setLayout(new javax.swing.BoxLayout(passwordPanel, javax.swing.BoxLayout.X_AXIS));
         passwordLabel.setText(" Encryption Panel ");
        passwordPanel.add(passwordLabel);
        add(passwordPanel, java.awt.BorderLayout.NORTH);
        
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.X_AXIS));
         encryptButton.setText(" Encrypt ");
        buttonPanel.add(passwordField,java.awt.BorderLayout.WEST);
        buttonPanel.add(encryptButton,java.awt.BorderLayout.EAST);
         encryptButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptActionPerformed(evt);
            }
        });
        buttonPanel.add(encryptButton);   
        add(buttonPanel,java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents
    
    private void encryptActionPerformed(java.awt.event.ActionEvent evt){
        
        System.out.println("Encryption Starts");
        //System.out.println("Actual Data:" +embededText);
        //System.out.println("Password for Text: "+passwordField.getText().toString());
        String key = passwordField.getText().toString();
        this.embededText = AESImpl.encrypt(embededText, key);
        this.setPassword(key);
        JOptionPane.showMessageDialog(this,embededText);
        //System.out.println("Encrypted Data:"+embededText);
       // System.out.println("Decrypted Message: "+AESImpl.decrypt(embededText, key));
        
    }
    
    
    public boolean doValidation() {
        
        //System.out.println(getEmbeddedText());
        
        return true;
    }

    /**
     * Getter for property comment.
     *
     * @return Value of property comment.
     */
    public java.lang.String getComment() {
        return comment;
    }
    
    public void setEmbeddedText(String embeddedText){
         embededText = embeddedText;
    }
    
    public java.lang.String getEmbeddedText(){
        return this.embededText;
    }

    /**
     * Getter for property password.
     *
     * @return Value of property password.
     */
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String pwd){
            this.password = pwd;
    }

    /**
     * Getter for property quality.
     *
     * @return Value of property quality.
     */
    //public int getQuality() {
      //  return quality;
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel qualityLabel;
     private javax.swing.JPasswordField passwordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JTextArea commentTextArea;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JPanel qualityPanel;
    private javax.swing.JButton encryptButton;
    // End of variables declaration//GEN-END:variables

}
